#!/bin/bash
apt update -y
apt upgrade -y
apt install build-essential cpanminus dyndns -y
cpanm Mojolicious
iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT  --to 8080
mojo daemon -l http://*:8080
